spring:
  application:
    name: zuul-server

#ribbon:
#  eureka:
#    enabled: true

server:
  port: 8762

#zuul:
#  routes:
#    books:
#      url: http://localhost:8090
#    eureka-client:
#      url: http://localhost:8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    eureka-client:
      path: /client/**
      serviceId: eureka-client
      stripPrefix: true
